version: "3"
services:
  poll:
    build: ./poll
    links:
      - redis
      - db
    depends_on:
      - redis
    ports:
      - "5000:80"
    networks:
      - poll-tier
    environment:
      - 0.0.0.0
    restart: always
  redis:
    image: redis:alpine
    expose:
      - 6379
    ports:
      - "6379:6379"
    networks:
      - poll-tier
      - back-tier
    restart: always
  worker:
    build: ./worker
    networks:
      - back-tier
    environment:
      - 0.0.0.0
    restart: always
  db:
    image: postgres:13.2
    networks:
      - result-tier
      - back-tier
    volumes:
      - db-data:/var/lib/postgresql/data
      - "./schema.sql:/docker-entrypoint-initdb.d/init.sql"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=password"
    restart: always
  result:
    build: ./result
    ports:
      - "5001:80"
    networks:
      - result-tier
    environment:
      - 0.0.0.0
    restart: always
networks:
  poll-tier:
  result-tier:
  back-tier:
volumes:
  db-data: